name: x86-Darwin

on: 
  push:
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        type: [Debug, Release]
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: |
          brew update
          brew install llvm
          pip3 install lit
      - name: Build HelloWorld
        run: |
          cd HelloWorld
          mkdir build && cd build
          cmake -DLT_LLVM_INSTALL_DIR="/usr/local/opt/llvm@14/" -DCMAKE_BUILD_TYPE=${{ matrix.type }} ../
          make -j2
      - name: Build llvm-tutor + run tests
        run: |
          cd $GITHUB_WORKSPACE
          mkdir build && cd build
          cmake -DLT_LLVM_INSTALL_DIR="/usr/local/opt/llvm@14/" -DCMAKE_BUILD_TYPE=${{ matrix.type }} ../
          make -j2
          lit test/
